### ISSUE TITLE
feature reqest: function/example of displaying a custom character

### ISSUE THREAD

**Issue by ExileFox** [felias-fogg/DotMatrix5x7#2]
Hello, I'd like to request a new function and/or example to be added to this library that would display a custom character, for example if someone wants to show the ¥ (Yen symbol) which could look like this:

![image](https://user-images.githubusercontent.com/2000703/148668404-d2ee6e9b-d93e-4b46-a4b5-6025e627b481.png)

**Comment by felias-fogg** [comment]
Hi,

if you would like to create your own symbols, you can use the website [http://dotmatrixtool.com/](http://dotmatrixtool.com/). Select the following parameters:
Width: 6
Height: 8
Byte Order: Column Major
Endian: Little Endian

Now you can can left click (to mark) and right click (to unmark) and produce your symbol in the left five columns and the upper seven rows. Press "Generate", and you get the code you have to fill into the font table (the first five bytes). For the Yen symbol that would be: 0x29, 0x2a, 0x7c, 0x2a, 0x29

Now, you can either use one of the entries in the standard font table in dotfont5x7.h or you can setup your own private font table, which needs to be a PROGMEM char array similar to the font5x7 array, and then use the setFont method in order to switch between the standard table and your new table.
